language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  matrix:
    - DJANGO="Django>=1.8,<1.9" # 1.8
    - DJANGO="Django>=1.9,<1.10" # 1.9
    - DJANGO="Django>=1.10,<1.11" # 1.10
    - DJANGO="Django>=1.11,<1.12" # 1.11
    - DJANGO="Django>=2.0,<2.1" # 2.0
    - DJANGO="Django>=2.1,<2.2" # 2.1
    - DJANGO="Django>=2.2,<3.0" # 2.2
    - DJANGO="Django>=3.0a1,<3.1" # 3.0

cache: pip

install:
  - pip install "$DJANGO" pipenv
  - pipenv lock -r > requirements.txt
  - pip install -r requirements.txt
  - pip install coveralls

matrix:
  exclude:
  - python: "3.4"
    env: DJANGO="Django>=2.1,<2.2" # 2.1
  - python: "3.4"
    env: DJANGO="Django>=1.9,<1.10" # 1.8
  - python: "3.4"
    env: DJANGO="Django>=3.0a1,<3.1" # 3.0
  - python: "3.5"
    env: DJANGO="Django>=3.0a1,<3.1" # 3.0

script:
  - coverage run --source=easy manage.py test

after_success:
  coveralls
